name: 'Prepare Environment for App Build'

inputs:
  xcode-version:
    description: 'Xcode version'
    required: true

runs:
  using: "composite"

  steps:
  - name: Select Xcode
    uses: maxim-lobanov/setup-xcode@v1
    with:
      xcode-version: ${{ inputs.xcode-version }}