name: Unit Tests

on:
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: 'macos-26'

    env:
      SCHEME: "BlackBoxFirebaseCrashlytics"
      OS_VERSION: "26.4"

    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - destination: "platform=iOS Simulator"
            platform: ios
            device: "iPhone 17"
            system_prefix: "iOS"
          - destination: "platform=OS X"
            platform: macos
          - destination: "platform=tvOS Simulator"
            platform: tvos
            device: "Apple TV 4K (3rd generation)"
            system_prefix: "tvOS"
          - destination: "platform=watchOS Simulator"
            platform: watchos
            device: "Apple Watch Ultra 3 (49mm)"
            system_prefix: "watchOS"

    steps:
    - name: Get source code
      uses: actions/checkout@v6

    - name: Prepare Environment for App Build
      uses: ./.github/actions/prepare_env_app_build

    - name: Resolve Dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Create Simulator
      id: create_simulator
      if: matrix.platform != 'macos'
      uses: ./.github/actions/create_sim
      with:
        name: ${{ matrix.device }}
        device: ${{ matrix.device }}
        system: ${{ matrix.system_prefix }}${{ env.OS_VERSION }}

    - name: Select Destination
      id: select-destination
      run: |
        if [ "${{ matrix.platform }}" = "macos" ]; then
          echo "dest=${{ matrix.destination }}" >> $GITHUB_OUTPUT
        else
          echo "dest=${{ matrix.destination }},id=${{ steps.create_simulator.outputs.uuid }}" >> $GITHUB_OUTPUT
        fi

    - name: Build
      run: >
        xcodebuild build-for-testing
        -scheme ${{ env.SCHEME }}
        -destination '${{ steps.select-destination.outputs.dest }}'
        SWIFT_SUPPRESS_WARNINGS=NO
        -quiet

    - name: Test
      run: >
        xcodebuild test-without-building
        -scheme ${{ env.SCHEME }}
        -destination '${{ steps.select-destination.outputs.dest }}'
        SWIFT_SUPPRESS_WARNINGS=NO
        -quiet

  # This allows us to have a branch protection rule for tests and deploys with matrix
  status-for-matrix:
    runs-on: 'ubuntu-latest'
    needs: tests
    if: always()
    steps:
      - name: Calculate matrix result
        run: |
          result="${{ needs.tests.result }}"
          if [[ $result == "success" ]]; then
            exit 0
          else
            exit 1
          fi
